[package]
name = "secure-binder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[alias]
# Define a command for watching and running
watch-run = "watch -x run"